function link() {
//Random Banners
 } ; l = new link() ; n = 0
//-----------------------------Database----------------------------
l[n++]= "<a href='mailto:fiction@galacticempire.net' target=`_top`><img src='http://www.galacticempire.net/gifs/submit_fic.gif' BORDER='0' ALT='Submit Fiction'></A>"
l[n++]= "<a href='mailto:art@galacticempire.net' target=`_top`><img src='http://www.galacticempire.net/gifs/submit_art.gif' BORDER='0' ALT='Submit Art'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/news_archive.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60.gif' BORDER='0' ALT='News'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/images.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60.gif' BORDER='0' ALT='Images'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/multimedia.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/multi-media_100x60.gif' BORDER='0' ALT='MultiMedia'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/interactive.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/interactive_map.gif' BORDER='0' ALT='Star Wars Galaxy - Interactive Map'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/fiction.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/fiction_100x60.gif' BORDER='0' ALT='Fiction'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/features.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60.gif' BORDER='0' ALT='Features'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/services.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/services_100x60.gif' BORDER='0' ALT='Services'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/misc.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/misc_100x60.gif' BORDER='0' ALT='Misc.'></A>"
l[n++]= "<a href='http://www.galacticempire.net/affiliates.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/affiliates_100x60.gif' BORDER='0' ALT='Affiliates'></A>"
l[n++]= "<a href='http://www.galacticempire.net/arch/archive.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/archives_100x60.gif' BORDER='0' ALT='Archives'></A>"
l[n++]= "<a href='mailto:fiction@galacticempire.net' target=`_top`><img src='http://www.galacticempire.net/gifs/submit_fic.gif' BORDER='0' ALT='Submit Fiction'></A>"
l[n++]= "<a href='mailto:art@galacticempire.net' target=`_top`><img src='http://www.galacticempire.net/gifs/submit_art.gif' BORDER='0' ALT='Submit Art'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/news_archive.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60.gif' BORDER='0' ALT='News'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/images.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60.gif' BORDER='0' ALT='Images'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/multimedia.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/multi-media_100x60.gif' BORDER='0' ALT='MultiMedia'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/interactive.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/interactive_map.gif' BORDER='0' ALT='Star Wars Galaxy - Interactive Map'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/fiction.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/fiction_100x60.gif' BORDER='0' ALT='Fiction'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/features.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60.gif' BORDER='0' ALT='Features'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/services.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/services_100x60.gif' BORDER='0' ALT='Services'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/misc.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/misc_100x60.gif' BORDER='0' ALT='Misc.'></A>"
l[n++]= "<a href='http://www.galacticempire.net/affiliates.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/affiliates_100x60.gif' BORDER='0' ALT='Affiliates'></A>"
l[n++]= "<a href='http://www.galacticempire.net/arch/archive.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/archives_100x60.gif' BORDER='0' ALT='Archives'></A>"
l[n++]= "<a href='http://radio.sonicnet.com/mymusiclisten.asp?name=GalacticEmpire' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60_genradio.gif' BORDER='0' ALT='G.E.N Radio'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/chat.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60_chat.gif' BORDER='0' ALT='Chat Screen'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/editorials.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60_editorials.gif' BORDER='0' ALT='Editorials'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/links.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60_links.gif' BORDER='0' ALT='Star Wars Links'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/review.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60_novel-reviews.gif' BORDER='0' ALT='Novel Reviews'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/fanclub/fc.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60_uk-fanclub.gif' BORDER='0' ALT='SW - UK Fan Club'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/uk_mag/sw.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60_uk-sw-mag.gif' BORDER='0' ALT='UK SW Magazine'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/barbican/barbi_1.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60_barbican.gif' BORDER='0' ALT='SW @ The Barbican'></A>"
l[n++]= "<a href='http://www.galacticempire.net/features/interactive.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/features_100x60_interactive-map.gif' BORDER='0' ALT='SW Interactive Map'></A>"
l[n++]= "<a href='http://www.galacticempire.net/fiction/fan_fiction.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/fiction_100x60_fan-fic.gif' BORDER='0' ALT='Fan Fiction'></A>"
l[n++]= "<a href='http://www.galacticempire.net/fiction/kessler.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/fiction_100x60_kessler.gif' BORDER='0' ALT='Kesslers Fiction'></A>"
l[n++]= "<a href='http://www.galacticempire.net/fiction/phoenix_tril.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/fiction_100x60_phoenix.gif' BORDER='0' ALT='The Phoenix Trilogy'></A>"
l[n++]= "<a href='http://www.galacticempire.net/fiction/oracle_tril.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/fiction_100x60_oracle.gif' BORDER='0' ALT='The Oracle Trilogy'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/episodei/tpm1.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_ep-i.gif' BORDER='0' ALT='Episode I'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/episodeii/scans_1.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_ep-ii.gif' BORDER='0' ALT='Episode II'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/novelart/novel1.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_novel-art.gif' BORDER='0' ALT='Novel Art / Covers'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/alta/one.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_alta.gif' BORDER='0' ALT='A Long Time Ago...'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/artwork/artwork1.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_sw-artwork.gif' BORDER='0' ALT='Star Wars Art-Work'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/concept/concept1.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_concept.gif' BORDER='0' ALT='Star Wars Concept Art'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/empire/imp1.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_empire.gif' BORDER='0' ALT='The Empire'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/fan_art/one.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_fanart.gif' BORDER='0' ALT='Fan Art-Work'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/videos/vid_1.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_vidart.gif' BORDER='0' ALT='SW Video Art-Work'></A>"
l[n++]= "<a href='http://www.galacticempire.net/images/rebel/reb1.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/images_100x60_rebel.gif' BORDER='0' ALT='Rebel Alliance'></A>"
l[n++]= "<a href='http://www.galacticempire.net/misc/privacy.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/misc_100x60_privacy.gif' BORDER='0' ALT='Privacy Statement'></A>"
l[n++]= "<a href='http://www.galacticempire.net/misc/disclaim.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/misc_100x60_disclaimer.gif' BORDER='0' ALT='Disclaimer'></A>"
l[n++]= "<a href='http://www.galacticempire.net/misc/webrings.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/misc_100x60_webrings.gif' BORDER='0' ALT='Web Rings'></A>"
l[n++]= "<a href='http://www.galacticempire.net/misc/siteinfo.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/misc_100x60_site-info.gif' BORDER='0' ALT='Site Information'></A>"
l[n++]= "<a href='http://www.galacticempire.net/misc/force_dance.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/misc_100x60_force-dance.gif' BORDER='0' ALT='Force Dance'></A>"
l[n++]= "<a href='http://www.galacticempire.net/misc/asteroid.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/misc_100x60_asteroids.gif' BORDER='0' ALT='Asteroids'></A>"
l[n++]= "<a href='http://www.galacticempire.net/multimedia/fonts.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/multimedia_100x60_sw-fonts.gif' BORDER='0' ALT='Star Wars Fonts'></A>"
l[n++]= "<a href='http://www.galacticempire.net/multimedia/wallpaper.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/multimedia_100x60_sw-wp.gif' BORDER='0' ALT='Star Wars Wallpapers'></A>"
l[n++]= "<a href='http://www.galacticempire.net/multimedia/scripts/scripts.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/multimedia_100x60_sw-scripts.gif' BORDER='0' ALT='Star Wars Scripts'></A>"
l[n++]= "<a href='http://www.galacticempire.net/multimedia/sounds/song.html' target=`_top`><img src='http://www.galacticempire.net/gifs/multimedia_100x60_track.gif' BORDER='0' ALT='Track of the Week'></A>"
l[n++]= "<a href='http://www.galacticempire.net/multimedia/radio.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/multimedia_100x60_radio.gif' BORDER='0' ALT='The Radio Plays'></A>"
l[n++]= "<a href='http://www.galacticempire.net/multimedia/realplayer.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/multimedia_100x60_realplayer.gif' BORDER='0' ALT='Real Player Files'></A>"
l[n++]= "<a href='http://www.galacticempire.net/multimedia/sounds/midi.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/multimedia_100x60_midi.gif' BORDER='0' ALT='Midi Files'></A>"
l[n++]= "<a href='http://www.galacticempire.net/multimedia/sounds/wavs.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/multimedia_100x60_wavs.gif' BORDER='0' ALT='Wav Files'></A>"
l[n++]= "<a href='http://www.galacticempire.net/services/ring.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/services_100x60_gen-webring.gif' BORDER='0' ALT='G.E.N Web Ring'></A>"
l[n++]= "<a href='http://www.galacticempire.net/services/banner_exchange.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/services_100x60_gen-banner-x.gif' BORDER='0' ALT='G.E.N Banner Xchange'></A>"
l[n++]= "<a href='http://www.galacticempire.net/services/gemail.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/services_100x60_ge-mail-info.gif' BORDER='0' ALT='GE Mail Info'></A>"
l[n++]= "<a href='http://mail.bigmailbox.com/users/galacticempirecouk/signup.cgi' target=`_blank`><img src='http://www.galacticempire.net/gifs/services_100x60_ge-co-uk-signup.gif' BORDER='0' ALT='@ge.co.uk - Sign-Up'></A>"
l[n++]= "<a href='http://mail.bigmailbox.com/users/galacticempirenet/signup.cgi' target=`_blank`><img src='http://www.galacticempire.net/gifs/services_100x60_ge-net-signup.gif' BORDER='0' ALT='@ge.net - Sign-Up'></A>"
l[n++]= "<a href='http://www.galacticempire.net/genm.htm' target=`_blank`><img src='http://www.galacticempire.net/gifs/services_100x60_gemail-login.gif' BORDER='0' ALT='GE Mail - Log-In'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/episodeii_news.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60_ep-ii.gif' BORDER='0' ALT='Episode II News'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/swcom_news.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60_sw-com.gif' BORDER='0' ALT='SW.Com News'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/games_news.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60_games.gif' BORDER='0' ALT='Games News'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/novel_news.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60_novel.gif' BORDER='0' ALT='Novel News'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/collecting_news.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60_collecting.gif' BORDER='0' ALT='Collecting News'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/misc_news.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60_misc.gif' BORDER='0' ALT='Misc. News'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/affiliate_news.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60_affiliate.gif' BORDER='0' ALT='Affiliate News'></A>"
l[n++]= "<a href='http://cgi.galacticempire.net/gen_news.shtml' target=`_top`><img src='http://www.galacticempire.net/gifs/news_100x60_gen.gif' BORDER='0' ALT='G.E.N News'></A>"
// just keep adding to database
//------------------------------------------------------------------
i=Math.floor(Math.random() * n) ; 
document.write( l[i] )
//-->
